name: Run and update dashboard

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python:
          - '3.13'

    steps:
      - name: Set up environment
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install nwb2bids with dandiset converter
        run: |
          python -m pip install --upgrade pip wheel
          pip install git+https://github.com/con/nwb2bids.git@add_dandiset_converter
          pip install dandi remfile

      - name: Run nwb2bids over Dandisets
        run: python scripts/run_nwb2bids_on_dandisets.py

      - name: Update dashboard
        run: python scripts/update_dashboard.py

      - name: Push changes to dashboard
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Send email notification on failure
        if: ${{ always() && failure() }}  # 'always' for if any 'needs' are cancelled/skipped
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "nwb2bids Dandiset Dashboard Update Failed"
          to: cody.c.baker.phd@gmail.com  # Add more with comma separation (no spaces)
          from: nwb2bids Dashboard
          body: |
            The scheduled run of nwb2bids updates encountered an issue, please check status at
            https://github.com/con/nwb2bids-dandisets-dashboard/actions/workflows/deploy_nwb2bids_on_dandisets.yml
