name: Run and update dashboard

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python:
          - '3.13'

    steps:
      - name: Set up environment
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install nwb2bids with dandiset converter
        run: |
          python -m pip install --upgrade pip wheel
          pip install git+https://github.com/con/nwb2bids.git@add_dandiset_converter
          pip install dandi remfile

      - name: Run nwb2bids over Dandisets
        run: python scripts/update_dashboard.py

      - name: Update dashboard
        run: python scripts/update_dashboard.py

      - name: Push changes to dashboard
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Send fail signal if changes were detected
        if: env.CHANGES == 'true'
        run: exit 1
